import { InvoiceDetail } from "@/lib/types";
import { money, fmtDate } from "@/lib/format";
import { APP_FULL_NAME } from "@/lib/brand";

export async function downloadAuditReportPDF(invoice: InvoiceDetail) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const margin = 56;
  let y = 64;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(`${APP_FULL_NAME} — Audit Report`, margin, y);
  y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110);
  doc.text(`Invoice ${invoice.invoiceNumber}  ·  Generated ${fmtDate(invoice.issueDate)}`, margin, y);
  doc.setTextColor(0);
  y += 30;

  function field(label: string, value: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text(label.toUpperCase(), margin, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.text(value, margin, y + 14);
    y += 34;
  }

  function wrapText(text: string, size = 11) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, 500);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 14;
  }

  const report = invoice.latestReport;
  const isClean = !report?.findings.length;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Summary", margin, y);
  y += 18;
  wrapText(report?.summary ?? "No audit has been run for this invoice yet.");

  if (report?.findings.length) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Detected Discrepancies", margin, y);
    y += 18;
    for (const f of report.findings) {
      wrapText(`${f.discrepancyType.replace(/_/g, " ")}: ${f.explanation}`);
    }
  }

  field("Vendor", invoice.vendorName);
  field("Consultant", `${invoice.consultantName ?? "—"}  (${invoice.project ?? "—"})`);
  field("Invoice Hours / Rate", `${invoice.hours ?? "—"} hrs @ $${invoice.hourlyRate ?? "—"}/hr = ${money(invoice.amount)}`);
  if (invoice.matchedTimesheet) {
    field(
      "QuickBooks Hours / Rate",
      `${invoice.matchedTimesheet.hours} hrs @ $${invoice.matchedTimesheet.hourlyRate}/hr = ${money(invoice.matchedTimesheet.hours * invoice.matchedTimesheet.hourlyRate)}`,
    );
  }
  field("Risk Score", `${invoice.riskScore ?? "—"} / 100  (${invoice.riskLabel ?? "Not audited"})`);
  field("Estimated Overpayment", money(invoice.overpay));
  if (invoice.confidence !== null) field("Match Confidence", `${invoice.confidence.toFixed(1)}%`);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Reviewer Notes", margin, y);
  y += 18;
  wrapText(
    isClean
      ? "No reviewer action required. Cleared for standard payment processing."
      : "Flagged by Audix's audit engine for finance review prior to payment release.",
  );

  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by Audix.", margin, 740);

  doc.save(`Audix_Audit_Report_${invoice.invoiceNumber}.pdf`);
}
